#Pytorch Basics

##Introduction
Pytorch is a deep learning framework that enables implementation of deep learning models

In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as okt

In [3]:
# Create some 'Matrices' as lists of lists
# 3 x 3
W = [
    [1, 1, 1],
    [1.5, 1.5, 1.5],
    [2, 2, 2]
]

# 3 x 1
x = [
    [6],
    [7],
    [8]
]

# 3 x 1
b = [
    [1],
    [1],
    [1]
]

# 3 x 1
y = [
    [1],
    [1],
    [1]
]

In [5]:
# Converting lists to numpy arrays
W_np = np.array(W)

x_np = np.array(x)

# Lets use function 'ones' to create an array of ones
b_np = np.ones((3, 1))

# Lets compute Wx +b using numpy
output = np.matmul(W_np, x_np) + b_np

print("Output shape:", output.shape)
print("Output:", output)




Output shape: (3, 1)
Output: [[22. ]
 [32.5]
 [43. ]]


In [6]:
# Similar to numpy
W_torch = torch.FloatTensor(W)

x_torch = torch.FloatTensor(x)

b_torch = torch.ones(3, 1)

output = torch.matmul(W_torch, x_torch) + b_torch

print("Output shape:", output.shape)
print("Output:", output)

Output shape: torch.Size([3, 1])
Output: tensor([[22.0000],
        [32.5000],
        [43.0000]])


In [7]:
torch.tensor(W).dtype

torch.float32

In [8]:
torch.tensor(x).dtype

torch.int64

In [9]:
# Conversion from numpy into pytorch and vice versa
np_array = np.random.random((3, 4))
print("numpy array:", np_array)

# Convert numpy array into tensor
torch_tensor = torch.FloatTensor(np_array)
print(torch_tensor)

# Convert torch tensor back to numpy array
np_arrray_2 = torch_tensor.numpy()
print("numpy array:", np_arrray_2)

numpy array: [[0.74575447 0.694081   0.33068089 0.99900005]
 [0.2017521  0.48664287 0.99671017 0.59401312]
 [0.58832475 0.42943154 0.41294713 0.48947742]]
tensor([[0.7458, 0.6941, 0.3307, 0.9990],
        [0.2018, 0.4866, 0.9967, 0.5940],
        [0.5883, 0.4294, 0.4129, 0.4895]])
numpy array: [[0.7457545  0.694081   0.33068088 0.9990001 ]
 [0.2017521  0.48664287 0.9967102  0.5940131 ]
 [0.5883247  0.42943156 0.41294712 0.48947743]]


In [10]:
# Basic elementwise operations
# Lets create a 2D tensor using torch.rand
y = torch.rand(4, 5)
print("Our 2D tensor:", y)

# We can perform normal scalar arithmetic on a tensor
print("Scalar Multiplication:", y * 10)
print("Addition and Square:", (y + 1) ** 2)
print("Addition:", y + y)
print("Addition and Division:", y/(y+y))

# We can use a combonation of functions and normal python arithmetic
print("Power and square root:", torch.sqrt(y ** 2))

# Tensors are objects and have functions
print(f"Min: {y.min()}\t Max: {y.max()}\t Std: {y.std()}\t Sum: {y.sum()}")

Our 2D tensor: tensor([[0.2273, 0.5745, 0.9259, 0.7307, 0.3776],
        [0.7953, 0.0467, 0.9034, 0.2353, 0.4092],
        [0.2028, 0.9067, 0.1711, 0.8145, 0.1292],
        [0.2710, 0.4368, 0.4910, 0.9744, 0.8632]])
Scalar Multiplication: tensor([[2.2731, 5.7447, 9.2587, 7.3072, 3.7756],
        [7.9527, 0.4668, 9.0338, 2.3534, 4.0924],
        [2.0279, 9.0673, 1.7113, 8.1448, 1.2919],
        [2.7095, 4.3680, 4.9096, 9.7440, 8.6320]])
Addition and Square: tensor([[1.5063, 2.4790, 3.7090, 2.9954, 1.8977],
        [3.2230, 1.0955, 3.6229, 1.5261, 1.9860],
        [1.4467, 3.6356, 1.3715, 3.2923, 1.2751],
        [1.6153, 2.0644, 2.2230, 3.8983, 3.4715]])
Addition: tensor([[0.4546, 1.1489, 1.8517, 1.4614, 0.7551],
        [1.5905, 0.0934, 1.8068, 0.4707, 0.8185],
        [0.4056, 1.8135, 0.3423, 1.6290, 0.2584],
        [0.5419, 0.8736, 0.9819, 1.9488, 1.7264]])
Addition and Division: tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
    

In [ ]:
# Tensor operations
tensor_1 = torch.rand(3, 3, 3)
tensor_2 = torch.rand(3, 3, 3)

# Addition of two tensors
print("Addition:", tensor_1 + tensor_2)

# batch Multiplication
print("Batch Multiplication:", torch.bmm(tensor_1, tensor_2))

In [11]:
# Lets create a more interesting tensor
tensor_3 = torch.rand(2, 4, 5)

# We can swap tensor dimentions
print("Original tensor:", tensor_3)
print("Original tensor shape:", tensor_3.shape)

# We can transpose tensor as follows
transposed_tensor_3 = tensor_3.transpose(0, 2)
print("Transposed tensor:", transposed_tensor_3)
print("Transposed tensor shape:", transposed_tensor_3.shape)

Original tensor: tensor([[[0.5600, 0.3923, 0.3368, 0.3188, 0.5633],
         [0.0326, 0.9750, 0.3185, 0.1437, 0.0887],
         [0.8491, 0.1642, 0.1721, 0.0584, 0.3089],
         [0.8318, 0.6682, 0.1231, 0.5838, 0.5607]],

        [[0.4032, 0.5371, 0.8027, 0.6567, 0.5139],
         [0.8255, 0.8844, 0.4168, 0.9622, 0.6535],
         [0.8819, 0.2211, 0.1585, 0.7467, 0.1179],
         [0.4076, 0.5447, 0.4378, 0.1726, 0.7961]]])
Original tensor shape: torch.Size([2, 4, 5])
Transposed tensor: tensor([[[0.5600, 0.4032],
         [0.0326, 0.8255],
         [0.8491, 0.8819],
         [0.8318, 0.4076]],

        [[0.3923, 0.5371],
         [0.9750, 0.8844],
         [0.1642, 0.2211],
         [0.6682, 0.5447]],

        [[0.3368, 0.8027],
         [0.3185, 0.4168],
         [0.1721, 0.1585],
         [0.1231, 0.4378]],

        [[0.3188, 0.6567],
         [0.1437, 0.9622],
         [0.0584, 0.7467],
         [0.5838, 0.1726]],

        [[0.5633, 0.5139],
         [0.0887, 0.6535],
         [0.3

In [13]:
# Indexing
# Create a 4D tensor
tensor = torch.rand(2, 3, 1, 4)

# Select last element of dim0
print("Last element of dim0:", tensor[-1])

# Select all elemnts in dim0
# The 2nd element of dim1
# The 1st element of dim2
# The 3rd element of dim3
print("Indexed elements:", tensor[:, 1, 0, 2])

# Select 1st element from dim0
# The 2nd elemnt of dim1
print("Indexed elemnts:", tensor[0, 1])

# Select all elements from dim0
# The 2nd element of dim1
# The 1st element of dim2
# The 3rd element of dim3
print("Indexed elements:", tensor[:, 1, 0, 2])

Last element of dim0: tensor([[[0.2285, 0.1995, 0.8431, 0.2430]],

        [[0.2437, 0.3660, 0.6045, 0.0132]],

        [[0.5802, 0.3566, 0.5938, 0.1747]]])
Indexed elements: tensor([0.7985, 0.6045])
Indexed elemnts: tensor([[0.5703, 0.2807, 0.7985, 0.2731]])
Indexed elements: tensor([0.7985, 0.6045])


In [14]:
# Tensor Description

# Lets create a large 4D tensor
tensor = torch.rand(3, 5, 3, 2)

# View the number of elements in every dimension
print("Tensor shape:", tensor.shape)

# Also use size() to get the shape of a  tensor
print("Tensor shape:", tensor.size())

# View total number of elements in a tensor
print("Total number of elements in a tensor:", tensor.numel())

# View number of dimensions
print("Number of dimensions of a tensor:", tensor.ndim)

Tensor shape: torch.Size([3, 5, 3, 2])
Tensor shape: torch.Size([3, 5, 3, 2])
Total number of elements in a tensor: 90
Number of dimensions of a tensor: 4


In [16]:
# Reshaping

# Let us reshape our 2D tensor
print("Reshape to 3x30:", tensor.reshape(3, 30))

# Let us flatten our tensor into 1D tensor
print("Flattened tensor:", tensor.flatten())

# Let is reshape int 10, whatever
print("Reshaped tensor into 10xwhatever:", tensor.reshape(10, -1))

Reshape to 3x30: tensor([[0.8645, 0.2700, 0.3654, 0.3149, 0.5697, 0.9797, 0.5576, 0.4756, 0.7761,
         0.5547, 0.2647, 0.2775, 0.7836, 0.6161, 0.9882, 0.1077, 0.7268, 0.8964,
         0.4024, 0.8445, 0.2857, 0.7473, 0.7414, 0.9851, 0.9718, 0.4182, 0.1455,
         0.4635, 0.5408, 0.5409],
        [0.4489, 0.3846, 0.6211, 0.0176, 0.7443, 0.2036, 0.4177, 0.5245, 0.4443,
         0.7930, 0.8229, 0.4333, 0.9144, 0.8422, 0.0096, 0.2146, 0.9692, 0.3228,
         0.9849, 0.6887, 0.2696, 0.5062, 0.2783, 0.4446, 0.1681, 0.9933, 0.7770,
         0.9956, 0.2829, 0.7609],
        [0.7793, 0.9173, 0.1154, 0.6977, 0.1795, 0.2494, 0.2402, 0.9446, 0.5834,
         0.5661, 0.8031, 0.0304, 0.4986, 0.9368, 0.3132, 0.8191, 0.7657, 0.9424,
         0.6521, 0.4680, 0.9781, 0.7742, 0.4606, 0.1190, 0.5478, 0.0639, 0.9959,
         0.1323, 0.2133, 0.1917]])
Flattened tensor: tensor([0.8645, 0.2700, 0.3654, 0.3149, 0.5697, 0.9797, 0.5576, 0.4756, 0.7761,
        0.5547, 0.2647, 0.2775, 0.7836, 0.6161, 0.988

In [18]:
# Unsqueezing

tensor = torch.rand(3, 2)

# View tensor shape
print("Tensor shape:", tensor.shape)

# Add empty dimension
print("Add an empty dimension to dim3:", tensor.unsqueeze(2).shape)

# Add an empty dimention into our tensor
print("Add empty dim into dim2 of our tensor:", tensor.unsqueeze(1).shape)

Tensor shape: torch.Size([3, 2])
Add an empty dimension to dim3: torch.Size([3, 2, 1])
Add empty dim into dim2 of our tensor: torch.Size([3, 1, 2])


In [20]:
# Squeezing

# Lets create a 4D tensor with some empty dimension
tensor = torch.rand(1, 3, 1, 2)

# View original tensor shape
print("Tensor shape:", tensor.shape)

# Remove empty dimension at dim3
print("Tensor with empty dimension dim3 removed:", tensor.squeeze(2).shape)

# Remove empty dimension at dim1
print("Tensor shape with empty dimension dim1 removed:", tensor.squeeze(0).shape)

# Remove all empty dim from our tensor
print("Tensor with all empty dimensions removed:", tensor.squeeze())



Tensor shape: torch.Size([1, 3, 1, 2])
Tensor with empty dimension dim3 removed: torch.Size([1, 3, 2])
Tensor shape with empty dimension dim1 removed: torch.Size([3, 1, 2])
Tensor with all empty dimensions removed: tensor([[0.5220, 0.4349],
        [0.8164, 0.9817],
        [0.2937, 0.4353]])


In [21]:
# Broadcasting
tensor_1 = torch.rand(1, 4, 3, 1)
tensor_2 = torch.rand(3, 4, 1, 4)

print("Tensor 1 shape:", tensor_1.shape)
print("Tensor 2 shape:", tensor_2.shape)

tensor_3 = tensor_1 + tensor_2

print("Resulting tensor 3 shape", tensor_3.shape)

Tensor 1 shape: torch.Size([1, 4, 3, 1])
Tensor 2 shape: torch.Size([3, 4, 1, 4])
Resulting tensor 3 shape torch.Size([3, 4, 3, 4])
